In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
import matplotlib.pyplot as plt
%matplotlib notebook
from scipy.stats import linregress




df = pd.read_csv('/datc/opschaler/output/P01S01W0378_gas_electricity_weather.csv',header = 0, delimiter="\t")

In [8]:
df.head()

,datetime,eMeter,eMeterReturn,eMeterLow,eMeterLowReturn,ePower,ePowerReturn,gasMeter,gasPower,DD,...,P,Q,RG,SQ,T,T10,TD,U,VV,WW
0,2017-03-07 07:33:50,1345.063,0.0,1645.075,0.0,366.0,0.0,521.065531,0.001436,286.708333,...,1013.338333,22.6,0.0,0.0,6.576667,6.238333,6.0,95.616667,11570.0,2.0
1,2017-03-07 07:34:00,1345.064,0.0,1645.075,0.0,368.0,0.0,521.066967,0.001436,286.800000,...,1013.340000,22.8,0.0,0.0,6.580000,6.240000,6.0,95.600000,11560.0,2.0
2,2017-03-07 07:34:10,1345.065,0.0,1645.075,0.0,366.0,0.0,521.068403,0.001436,286.891667,...,1013.341667,23.0,0.0,0.0,6.583333,6.241667,6.0,95.583333,11550.0,2.0
3,2017-03-07 07:34:20,1345.066,0.0,1645.075,0.0,363.0,0.0,521.069839,0.001436,286.983333,...,1013.343333,23.2,0.0,0.0,6.586667,6.243333,6.0,95.566667,11540.0,2.0
4,2017-03-07 07:34:30,1345.071,0.0,1645.075,0.0,2481.0,0.0,521.071275,0.001436,287.075000,...,1013.345000,23.4,0.0,0.0,6.590000,6.245000,6.0,95.550000,11530.0,2.0

In [50]:
df.describe(include = 'all')

,eMeter,eMeterReturn,eMeterLow,eMeterLowReturn,ePower,ePowerReturn,DD,FH,FF,FX,...,U,WW,IX,M,R,S,O,Y,gasMeter,gasPower
count,180212.000000,180212.0,180212.000000,180212.0,180212.000000,180212.0,183155.000000,183155.000000,183155.000000,183155.000000,...,183155.000000,488,183155.000000,183155.000000,183155.000000,183155.0,183155.0,183155.000000,183155.000000,1.831550e+05
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,3772.072393,0.0,3943.560832,0.0,459.073052,0.0,176.494707,45.793263,45.890986,76.746608,...,78.482715,NaN,5.526767,0.026535,0.101226,0.0,0.0,0.001966,1628.126125,1.016285e-01
std,32.097010,0.0,36.042886,0.0,452.841780,0.0,99.016124,26.949537,26.984437,42.740694,...,15.162331,NaN,0.825656,0.155541,0.292251,0.0,0.0,0.036146,14.939726,9.933911e-02
min,3717.472000,0.0,3883.382000,0.0,238.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,36.000000,NaN,5.000000,0.000000,0.000000,0.0,0.0,0.000000,1599.838344,-9.094947e-13
25%,3737.922000,0.0,3918.327750,0.0,319.000000,0.0,86.000000,24.027778,24.805556,43.972222,...,67.683333,NaN,5.000000,0.000000,0.000000,0.0,0.0,0.000000,1615.840000,3.523611e-02
50%,3775.712000,0.0,3939.233500,0.0,350.000000,0.0,195.833333,40.000000,40.000000,70.000000,...,82.133333,NaN,5.000000,0.000000,0.000000,0.0,0.0,0.000000,1626.853000,5.750000e-02
75%,3801.514250,0.0,3973.161000,0.0,414.000000,0.0,245.777778,66.138889,64.666667,110.000000,...,90.483333,NaN,6.188889,0.000000,0.000000,0.0,0.0,0.000000,1641.571008,1.489681e-01
max,3830.551000,0.0,4003.787000,0.0,7765.000000,0.0,990.000000,120.000000,140.000000,210.000000,...,100.000000,NaN,7.000000,1.000000,1.000000,0.0,0.0,1.000000,1651.931000,6.470000e-01

In [51]:
# Nodig voor latex rendering
from matplotlib import rc
rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
rc('text', usetex=True)
plt.rc('text', usetex=True)
plt.rc('font', family='serif')

In [ ]:
a = pd.DataFrame()
a['eMeter'] = df['ePower']
a['gasMeter'] = df['gasPower']

In [52]:
plt.close()
label_tekst = 'Sample 1-%s: $B$=%s' % (sample, B)
#plt.errorbar(a['I'], a['U'], df['dU_H'], df['dI_plaat'], 'o', markeredgewidth=1, markeredgecolor='r',markerfacecolor='None', label=label_tekst, capsize=3, elinewidth=1, color='r',markersize=5)
plt.errorbar(a['eMeter'], a['gasMeter'], df['ePower'], df['gasPower'], '.', label=label_tekst, capsize=3, elinewidth=0.5, color='crimson')


#fit plotten
fit = linregress(a['eMeter'], a['gasMeter'])

R_H = fit[0]*10**-6*(d/B)*10**11
n = 1/(R_H*e)*10**28
n = str(n)[:3]
fit_label='Fit: $U_H$($I$)=%.3f\cdot $I$ +%.3f \quad \n R$^2$=%.4f \qquad $\mathrm{stderr}$=%.3f \n $R_H$=%.3s \cdot 10^{11} \quad $n$=' % (fit[0], fit[1], fit[2], fit[4], R_H)+n+'\cdot 10^{28}'
plt.plot(a['eMeter'], fit[0]*a['eMeter']+fit[1], '-', label=fit_label, color='crimson')

plt.legend()
plt.grid()
plt.xlabel('E $I$ [Kw/h]')
plt.ylabel('E $U_H$ \mathrm{[\mu V]}}')

#correcte opmaak
tn.PRECISION_X = 3
tn.PRECISION_Y = 3
tn.fix_axis(plt.gca())

fit
print(R_H)
print(n)
plt.savefig('output\\sample1-'+str(sample)+'.png', dpi=200)

NameError: name 'sample' is not defined