In [8]:
#step 1 import packages/libraries
import sklearn as sk 
from sklearn import linear_model   #I am performing a linear regression, if it was multi_lin I would use different packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import style
from sklearn import svm
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
%matplotlib inline

#step 2 import csv, I use dwelling 8655 which is the most complete dwelling
dir = '//datc//opschaler//combined_gas_smart_weather_dfs//processed//'
dwelling_id = 'P01S01W5855_hour'
df = pd.read_csv(dir+dwelling_id+'.csv', delimiter='\t', parse_dates=['datetime'])
df = df.set_index(['datetime'])
df.head()

,eMeter,eMeterReturn,eMeterLow,eMeterLowReturn,ePower,ePowerReturn,gasMeter,DD,DR,FF,...,RG,SQ,T,T10,TD,U,VV,WW,dwelling,gasPower
datetime,,,,,,,,,,,,,,,,,,,,,
2017-03-07 07:00:00,NaN,NaN,NaN,NaN,NaN,NaN,2073.335,283.46667,0.0,2.076667,...,0.0,0.0,5.516667,4.400000,4.916666,95.166664,10295.000,4.666666,P01S01W5855,NaN
2017-03-07 08:00:00,2458.056,0.0,2370.064,0.0,477.85837,0.0,2073.933,273.10000,0.0,2.106667,...,0.0,0.0,5.933333,5.083334,5.216667,94.500000,10565.000,3.333333,P01S01W5855,0.598145
2017-03-07 09:00:00,2458.288,0.0,2370.064,0.0,232.49167,0.0,2074.427,281.45000,0.0,2.453333,...,0.0,0.0,6.466667,5.966667,5.800000,95.000000,11416.667,2.000000,P01S01W5855,0.493896
2017-03-07 10:00:00,2459.166,0.0,2370.064,0.0,880.23050,0.0,2074.991,282.10000,100.0,2.848333,...,0.0,0.0,7.016666,6.866667,5.916666,92.000000,11550.000,23.333334,P01S01W5855,0.563965
2017-03-07 11:00:00,2459.424,0.0,2370.064,0.0,251.95273,0.0,2075.398,286.85000,2.0,4.028333,...,0.0,0.0,7.566667,7.716667,6.183333,90.500000,13883.333,32.500000,P01S01W5855,0.406982