In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [77]:
#Allereerst moet de data worden ingelezen
df = pd.read_excel('/home/14109999/notebooks/KB-74-OPSCHALER/Personal_folders/Megan/Opdracht Lucas de Lange.xlsx',header = 0, delimiter="\t")

In [38]:
#vanaf hier begint de data cleaning. Shoutout naar datacamp
df.head()

,Year,Population1,Violent crime2,Violent crime rate,Murder and nonnegligent manslaughter,Murder and nonnegligent manslaughter rate,Rape (revised definition3),Rape (revised definition) rate3,Rape (legacy definition4),Rape (legacy definition) rate4,...,Aggravated assault,Aggravated assault rate,Property crime,Property crime rate,Burglary,Burglary rate,Larceny- theft,Larceny- theft rate,Motor vehicle theft,Motor vehicle theft rate
0,1997,267783607.0,1636096.0,611,18208.0,6.8,NaN,NaN,96153.0,35.9,...,1023201.0,382.1,11558475.0,4316.3,2460526,918.8,7743760.0,2891.8,1354189.0,505.7
1,1998,270248003.0,1533887.0,567.6,16974.0,6.3,NaN,NaN,93144.0,34.5,...,976583.0,361.4,10951827.0,4052.5,2332735,863.2,7376311.0,2729.5,1242781.0,459.9
2,1999,272690813.0,1426044.0,523,15522.0,5.7,NaN,NaN,89411.0,32.8,...,911740.0,334.3,10208334.0,3743.6,2100739,770.4,6955520.0,2550.7,1152075.0,422.5
3,2000,281421906.0,1425486.0,506.5,15586.0,5.5,NaN,NaN,90178.0,32.0,...,911706.0,324,10182584.0,3618.3,2050992,728.8,6971590.0,2477.3,1160002.0,412.2
4,20015,285317559.0,1439480.0,504.5,16037.0,5.6,NaN,NaN,90863.0,31.8,...,909023.0,318.6,10437189.0,3658.1,2116531,741.8,7092267.0,2485.7,1228391.0,430.5

In [39]:
print(df.columns)

Index(['Year', 'Population1', 'Violent\ncrime2', 'Violent \ncrime \nrate ',
       'Murder and\nnonnegligent \nmanslaughter',
       'Murder and \nnonnegligent \nmanslaughter \nrate ',
       'Rape\n(revised \ndefinition3)', 'Rape\n(revised \ndefinition) \nrate3',
       'Rape\n(legacy \ndefinition4)', 'Rape\n(legacy \ndefinition) \nrate4',
       'Robbery', 'Robbery \nrate ', 'Aggravated \nassault',
       'Aggravated \nassault rate ', 'Property \ncrime',
       'Property \ncrime \nrate ', 'Burglary', 'Burglary \nrate ',
       'Larceny-\ntheft', 'Larceny-\ntheft rate ', 'Motor \nvehicle \ntheft',
       'Motor \nvehicle \ntheft \nrate '],
      dtype='object')

In [40]:
df.columns = df.columns.str.upper()
print(df.columns)

Index(['YEAR', 'POPULATION1', 'VIOLENT\nCRIME2', 'VIOLENT \nCRIME \nRATE ',
       'MURDER AND\nNONNEGLIGENT \nMANSLAUGHTER',
       'MURDER AND \nNONNEGLIGENT \nMANSLAUGHTER \nRATE ',
       'RAPE\n(REVISED \nDEFINITION3)', 'RAPE\n(REVISED \nDEFINITION) \nRATE3',
       'RAPE\n(LEGACY \nDEFINITION4)', 'RAPE\n(LEGACY \nDEFINITION) \nRATE4',
       'ROBBERY', 'ROBBERY \nRATE ', 'AGGRAVATED \nASSAULT',
       'AGGRAVATED \nASSAULT RATE ', 'PROPERTY \nCRIME',
       'PROPERTY \nCRIME \nRATE ', 'BURGLARY', 'BURGLARY \nRATE ',
       'LARCENY-\nTHEFT', 'LARCENY-\nTHEFT RATE ', 'MOTOR \nVEHICLE \nTHEFT',
       'MOTOR \nVEHICLE \nTHEFT \nRATE '],
      dtype='object')

In [41]:
df = df.rename(columns = {'POPULATION1':'POPULATION','RAPE\n(REVISED \nDEFINITION3)':'RAPE','RAPE\n(REVISED \nDEFINITION) \nRATE3':'RAPE RATE'})
df.head()

,YEAR,POPULATION,VIOLENT CRIME2,VIOLENT CRIME RATE,MURDER AND NONNEGLIGENT MANSLAUGHTER,MURDER AND NONNEGLIGENT MANSLAUGHTER RATE,RAPE,RAPE RATE,RAPE (LEGACY DEFINITION4),RAPE (LEGACY DEFINITION) RATE4,...,AGGRAVATED ASSAULT,AGGRAVATED ASSAULT RATE,PROPERTY CRIME,PROPERTY CRIME RATE,BURGLARY,BURGLARY RATE,LARCENY- THEFT,LARCENY- THEFT RATE,MOTOR VEHICLE THEFT,MOTOR VEHICLE THEFT RATE
0,1997,267783607.0,1636096.0,611,18208.0,6.8,NaN,NaN,96153.0,35.9,...,1023201.0,382.1,11558475.0,4316.3,2460526,918.8,7743760.0,2891.8,1354189.0,505.7
1,1998,270248003.0,1533887.0,567.6,16974.0,6.3,NaN,NaN,93144.0,34.5,...,976583.0,361.4,10951827.0,4052.5,2332735,863.2,7376311.0,2729.5,1242781.0,459.9
2,1999,272690813.0,1426044.0,523,15522.0,5.7,NaN,NaN,89411.0,32.8,...,911740.0,334.3,10208334.0,3743.6,2100739,770.4,6955520.0,2550.7,1152075.0,422.5
3,2000,281421906.0,1425486.0,506.5,15586.0,5.5,NaN,NaN,90178.0,32.0,...,911706.0,324,10182584.0,3618.3,2050992,728.8,6971590.0,2477.3,1160002.0,412.2
4,20015,285317559.0,1439480.0,504.5,16037.0,5.6,NaN,NaN,90863.0,31.8,...,909023.0,318.6,10437189.0,3658.1,2116531,741.8,7092267.0,2485.7,1228391.0,430.5

In [42]:
df.isnull()

,YEAR,POPULATION,VIOLENT CRIME2,VIOLENT CRIME RATE,MURDER AND NONNEGLIGENT MANSLAUGHTER,MURDER AND NONNEGLIGENT MANSLAUGHTER RATE,RAPE,RAPE RATE,RAPE (LEGACY DEFINITION4),RAPE (LEGACY DEFINITION) RATE4,...,AGGRAVATED ASSAULT,AGGRAVATED ASSAULT RATE,PROPERTY CRIME,PROPERTY CRIME RATE,BURGLARY,BURGLARY RATE,LARCENY- THEFT,LARCENY- THEFT RATE,MOTOR VEHICLE THEFT,MOTOR VEHICLE THEFT RATE
0,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
21,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
22,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
23,False,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,True,True,True,True,True
24,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,True,True,True
25,False,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,True,True,True,True,True
26,False,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
27,True,True,True,False,True,True,True,True,True,True,...,True,False,True,True,True,True,True,True,True,True
28,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
30,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
31,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
32,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
33,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
34,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
35,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
36,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
37,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,False,True,True
38,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
39,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
40,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
41,True,True,True,False,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [43]:
df.head()

,YEAR,POPULATION,VIOLENT CRIME2,VIOLENT CRIME RATE,MURDER AND NONNEGLIGENT MANSLAUGHTER,MURDER AND NONNEGLIGENT MANSLAUGHTER RATE,RAPE,RAPE RATE,RAPE (LEGACY DEFINITION4),RAPE (LEGACY DEFINITION) RATE4,...,AGGRAVATED ASSAULT,AGGRAVATED ASSAULT RATE,PROPERTY CRIME,PROPERTY CRIME RATE,BURGLARY,BURGLARY RATE,LARCENY- THEFT,LARCENY- THEFT RATE,MOTOR VEHICLE THEFT,MOTOR VEHICLE THEFT RATE
0,1997,267783607.0,1636096.0,611,18208.0,6.8,NaN,NaN,96153.0,35.9,...,1023201.0,382.1,11558475.0,4316.3,2460526,918.8,7743760.0,2891.8,1354189.0,505.7
1,1998,270248003.0,1533887.0,567.6,16974.0,6.3,NaN,NaN,93144.0,34.5,...,976583.0,361.4,10951827.0,4052.5,2332735,863.2,7376311.0,2729.5,1242781.0,459.9
2,1999,272690813.0,1426044.0,523,15522.0,5.7,NaN,NaN,89411.0,32.8,...,911740.0,334.3,10208334.0,3743.6,2100739,770.4,6955520.0,2550.7,1152075.0,422.5
3,2000,281421906.0,1425486.0,506.5,15586.0,5.5,NaN,NaN,90178.0,32.0,...,911706.0,324,10182584.0,3618.3,2050992,728.8,6971590.0,2477.3,1160002.0,412.2
4,20015,285317559.0,1439480.0,504.5,16037.0,5.6,NaN,NaN,90863.0,31.8,...,909023.0,318.6,10437189.0,3658.1,2116531,741.8,7092267.0,2485.7,1228391.0,430.5

In [44]:
df_w0 = df.fillna(0)

In [45]:
df_w0.head()

,YEAR,POPULATION,VIOLENT CRIME2,VIOLENT CRIME RATE,MURDER AND NONNEGLIGENT MANSLAUGHTER,MURDER AND NONNEGLIGENT MANSLAUGHTER RATE,RAPE,RAPE RATE,RAPE (LEGACY DEFINITION4),RAPE (LEGACY DEFINITION) RATE4,...,AGGRAVATED ASSAULT,AGGRAVATED ASSAULT RATE,PROPERTY CRIME,PROPERTY CRIME RATE,BURGLARY,BURGLARY RATE,LARCENY- THEFT,LARCENY- THEFT RATE,MOTOR VEHICLE THEFT,MOTOR VEHICLE THEFT RATE
0,1997,267783607.0,1636096.0,611,18208.0,6.8,0,0.0,96153.0,35.9,...,1023201.0,382.1,11558475.0,4316.3,2460526,918.8,7743760.0,2891.8,1354189.0,505.7
1,1998,270248003.0,1533887.0,567.6,16974.0,6.3,0,0.0,93144.0,34.5,...,976583.0,361.4,10951827.0,4052.5,2332735,863.2,7376311.0,2729.5,1242781.0,459.9
2,1999,272690813.0,1426044.0,523,15522.0,5.7,0,0.0,89411.0,32.8,...,911740.0,334.3,10208334.0,3743.6,2100739,770.4,6955520.0,2550.7,1152075.0,422.5
3,2000,281421906.0,1425486.0,506.5,15586.0,5.5,0,0.0,90178.0,32.0,...,911706.0,324,10182584.0,3618.3,2050992,728.8,6971590.0,2477.3,1160002.0,412.2
4,20015,285317559.0,1439480.0,504.5,16037.0,5.6,0,0.0,90863.0,31.8,...,909023.0,318.6,10437189.0,3658.1,2116531,741.8,7092267.0,2485.7,1228391.0,430.5

In [46]:
df_w0.tail()

,YEAR,POPULATION,VIOLENT CRIME2,VIOLENT CRIME RATE,MURDER AND NONNEGLIGENT MANSLAUGHTER,MURDER AND NONNEGLIGENT MANSLAUGHTER RATE,RAPE,RAPE RATE,RAPE (LEGACY DEFINITION4),RAPE (LEGACY DEFINITION) RATE4,...,AGGRAVATED ASSAULT,AGGRAVATED ASSAULT RATE,PROPERTY CRIME,PROPERTY CRIME RATE,BURGLARY,BURGLARY RATE,LARCENY- THEFT,LARCENY- THEFT RATE,MOTOR VEHICLE THEFT,MOTOR VEHICLE THEFT RATE
37,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,0.0,0,0,0.0,0.0,,0.0,0.0
38,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,0.0,0,0,0.0,0.0,0,0.0,0.0
39,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,0.0,0,0,0.0,0.0,0,0.0,0.0
40,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,0.0,0,0,0.0,0.0,0,0.0,0.0
41,0,0.0,0.0,,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,0.0,0,0,0.0,0.0,0,0.0,0.0

In [47]:
df.head()

,YEAR,POPULATION,VIOLENT CRIME2,VIOLENT CRIME RATE,MURDER AND NONNEGLIGENT MANSLAUGHTER,MURDER AND NONNEGLIGENT MANSLAUGHTER RATE,RAPE,RAPE RATE,RAPE (LEGACY DEFINITION4),RAPE (LEGACY DEFINITION) RATE4,...,AGGRAVATED ASSAULT,AGGRAVATED ASSAULT RATE,PROPERTY CRIME,PROPERTY CRIME RATE,BURGLARY,BURGLARY RATE,LARCENY- THEFT,LARCENY- THEFT RATE,MOTOR VEHICLE THEFT,MOTOR VEHICLE THEFT RATE
0,1997,267783607.0,1636096.0,611,18208.0,6.8,NaN,NaN,96153.0,35.9,...,1023201.0,382.1,11558475.0,4316.3,2460526,918.8,7743760.0,2891.8,1354189.0,505.7
1,1998,270248003.0,1533887.0,567.6,16974.0,6.3,NaN,NaN,93144.0,34.5,...,976583.0,361.4,10951827.0,4052.5,2332735,863.2,7376311.0,2729.5,1242781.0,459.9
2,1999,272690813.0,1426044.0,523,15522.0,5.7,NaN,NaN,89411.0,32.8,...,911740.0,334.3,10208334.0,3743.6,2100739,770.4,6955520.0,2550.7,1152075.0,422.5
3,2000,281421906.0,1425486.0,506.5,15586.0,5.5,NaN,NaN,90178.0,32.0,...,911706.0,324,10182584.0,3618.3,2050992,728.8,6971590.0,2477.3,1160002.0,412.2
4,20015,285317559.0,1439480.0,504.5,16037.0,5.6,NaN,NaN,90863.0,31.8,...,909023.0,318.6,10437189.0,3658.1,2116531,741.8,7092267.0,2485.7,1228391.0,430.5

In [48]:
df_drop = df.dropna()

In [49]:
df_drop.head()

,YEAR,POPULATION,VIOLENT CRIME2,VIOLENT CRIME RATE,MURDER AND NONNEGLIGENT MANSLAUGHTER,MURDER AND NONNEGLIGENT MANSLAUGHTER RATE,RAPE,RAPE RATE,RAPE (LEGACY DEFINITION4),RAPE (LEGACY DEFINITION) RATE4,...,AGGRAVATED ASSAULT,AGGRAVATED ASSAULT RATE,PROPERTY CRIME,PROPERTY CRIME RATE,BURGLARY,BURGLARY RATE,LARCENY- THEFT,LARCENY- THEFT RATE,MOTOR VEHICLE THEFT,MOTOR VEHICLE THEFT RATE
16,2013,316497531.0,1168298.0,369.1,14319.0,4.5,113695,35.9,82109.0,25.9,...,726777.0,229.6,8651892.0,2733.6,1932139,610.5,6019465.0,1901.9,700288.0,221.3
17,2014,318907401.0,1153022.0,361.6,14164.0,4.4,118027,37.0,84864.0,26.6,...,731089.0,229.2,8209010.0,2574.1,1713153,537.2,5809054.0,1821.5,686803.0,215.4
18,20156,320896618.0,1199310.0,373.7,15883.0,4.9,126134,39.3,91261.0,28.4,...,764057.0,238.1,8024115.0,2500.5,1587564,494.7,5723488.0,1783.6,713063.0,222.2
19,2016,323127513.0,1248185.0,386.3,17250.0,5.3,130603,40.4,95730.0,29.6,...,803007.0,248.5,7919035.0,2450.7,1515096,468.9,5638455.0,1745,765484.0,236.9

In [50]:
df_drop_with_condition = df.dropna(thresh=2)

In [51]:
df_drop_with_condition.shape

(24, 22)

In [58]:
df.dtypes

YEAR                                                 object
POPULATION                                          float64
VIOLENT\nCRIME2                                     float64
VIOLENT \nCRIME \nRATE                               object
MURDER AND\nNONNEGLIGENT \nMANSLAUGHTER             float64
MURDER AND \nNONNEGLIGENT \nMANSLAUGHTER \nRATE     float64
RAPE                                                 object
RAPE RATE                                           float64
RAPE\n(LEGACY \nDEFINITION4)                        float64
RAPE\n(LEGACY \nDEFINITION) \nRATE4                 float64
ROBBERY                                             float64
ROBBERY \nRATE                                      float64
AGGRAVATED \nASSAULT                                float64
AGGRAVATED \nASSAULT RATE                            object
PROPERTY \nCRIME                                    float64
PROPERTY \nCRIME \nRATE                              object
BURGLARY                                             object
BURGLARY \nRATE                                     float64
LARCENY-\nTHEFT                                     float64
LARCENY-\nTHEFT RATE                                 object
MOTOR \nVEHICLE \nTHEFT                             float64
MOTOR \nVEHICLE \nTHEFT \nRATE                      float64
dtype: object

In [72]:
#Ik heb alle NaN's weggehaald, maar welke plot ik ook pak hij doet nietsssssssssss, pakt die nummers niet nummeric werkt ook niet, 
#covert object to float64 werkt ook niet, andere opties werken ook niet ....sad