In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
import sklearn as sk


df = pd.read_csv('/datc/opschaler/output/P01S01W0378_gas_electricity_weather.csv',header = 0, delimiter="\t")

In [20]:
df.head()

,eMeter,eMeterReturn,eMeterLow,eMeterLowReturn,ePower,ePowerReturn,DD,FH,FF,FX,...,U,WW,IX,M,R,S,O,Y,gasMeter,gasPower
0,3717.472,0.0,3883.382,0.0,376.0,0.0,255.222222,30.0,32.388889,60.0,...,81.761111,NaN,5.0,0.0,0.0,0.0,0.0,0.0,1599.838344,0.194
1,3717.473,0.0,3883.382,0.0,381.0,0.0,255.166667,30.0,32.416667,60.0,...,81.758333,NaN,5.0,0.0,0.0,0.0,0.0,0.0,1599.838883,0.194
2,3717.474,0.0,3883.382,0.0,378.0,0.0,255.111111,30.0,32.444444,60.0,...,81.755556,NaN,5.0,0.0,0.0,0.0,0.0,0.0,1599.839422,0.194
3,3717.475,0.0,3883.382,0.0,376.0,0.0,255.055556,30.0,32.472222,60.0,...,81.752778,NaN,5.0,0.0,0.0,0.0,0.0,0.0,1599.839961,0.194
4,3717.476,0.0,3883.382,0.0,380.0,0.0,255.000000,30.0,32.500000,60.0,...,81.750000,NaN,5.0,0.0,0.0,0.0,0.0,0.0,1599.840500,0.194

In [23]:
linear_model.df()

AttributeError: module 'sklearn.linear_model' has no attribute 'df'