In [7]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
import matplotlib.pyplot as plt
%matplotlib inline 

df = pd.read_csv("/datc/opschaler/combined_dfs_gas_smart_weather/P01S01W0378_merged_gas_smart_weather.csv",header=0,delimiter="\t",parse_dates = ['datetime'])

In [8]:
df.head()

,datetime,eMeter,eMeterReturn,eMeterLow,eMeterLowReturn,ePower,ePowerReturn,gasMeter,gasPower,DD,...,P,Q,RG,SQ,T,T10,TD,U,VV,WW
0,2017-03-07 07:33:50,1345.063,0.0,1645.075,0.0,366.0,0.0,521.065531,0.001436,286.708333,...,1013.338333,22.6,0.0,0.0,6.576667,6.238333,6.0,95.616667,11570.0,2.0
1,2017-03-07 07:34:00,1345.064,0.0,1645.075,0.0,368.0,0.0,521.066967,0.001436,286.800000,...,1013.340000,22.8,0.0,0.0,6.580000,6.240000,6.0,95.600000,11560.0,2.0
2,2017-03-07 07:34:10,1345.065,0.0,1645.075,0.0,366.0,0.0,521.068403,0.001436,286.891667,...,1013.341667,23.0,0.0,0.0,6.583333,6.241667,6.0,95.583333,11550.0,2.0
3,2017-03-07 07:34:20,1345.066,0.0,1645.075,0.0,363.0,0.0,521.069839,0.001436,286.983333,...,1013.343333,23.2,0.0,0.0,6.586667,6.243333,6.0,95.566667,11540.0,2.0
4,2017-03-07 07:34:30,1345.071,0.0,1645.075,0.0,2481.0,0.0,521.071275,0.001436,287.075000,...,1013.345000,23.4,0.0,0.0,6.590000,6.245000,6.0,95.550000,11530.0,2.0

In [9]:
#collect x and y

In [42]:

X = df['ePower'].values
Y = df['gasPower'].values

mean_x = np.mean(X)
mean_y = np.mean(Y)

#total number of the values
m = len(X)

numer = 0
denom = 0
for i in range(m):
    numer += (X[i]-mean_x)*([Y[i]-mean_y])
    denom += (X[i]-mean_x)**2
b1 = numer / denom
b0 = mean_y-(b1*mean_x)
#print coefficients
print(b1,b0)

TypeError: 'numpy.float64' object cannot be interpreted as an integer