In [13]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#importing my Opschaler module
import sys
sys.path.append('/home/16080696/notebooks/KB-74-OPSCHALER/')
import Opschaler as op

from sklearn import metrics
from sklearn.model_selection import train_test_split


import tensorflow as tf
from keras.layers.core import Dense, Activation
from keras.models import Sequential
from keras.callbacks import EarlyStopping

In [14]:
df = pd.read_csv("/datc/opschaler/combined_gas_smart_weather_dfs/processed/all_dwellings_combined_hour.csv",delimiter="\t", parse_dates = ['datetime'])

df = df.set_index(['datetime'])
#making the gaspower more readable (scaling)
df['gasPower'] = df['gasPower']*10
df = df.dropna()
df = df.resample('1D').mean()
df.head()

,eMeter,eMeterReturn,eMeterLow,eMeterLowReturn,ePower,ePowerReturn,gasMeter,DD,DR,FF,...,Q,RG,SQ,T,T10,TD,U,VV,WW,gasPower
datetime,,,,,,,,,,,,,,,,,,,,,
2017-02-22,1556.361003,0.0,1803.676799,0.0,185.730438,0.0,1678.554576,243.831944,444.333333,8.236250,...,30.708333,1.112500,0.000000,9.236111,8.973611,8.283333,93.319444,9911.805583,54.069444,2.562459
2017-02-23,1558.435883,0.0,1805.226395,0.0,173.374907,0.0,1685.894847,239.148194,265.916667,11.608438,...,24.312500,0.461319,0.149737,8.590000,8.163889,6.441597,86.511805,12887.305430,41.759722,4.857127
2017-02-24,1561.837229,0.0,1806.231979,0.0,246.992340,0.0,1694.890589,278.093543,45.766667,5.032826,...,107.562499,0.054306,2.962413,4.746250,3.968194,2.241736,83.740972,28850.902303,13.997222,2.768300
2017-02-25,1564.963013,0.0,1808.506632,0.0,150.144606,0.0,1698.313894,202.265418,14.750000,6.502271,...,49.312501,0.002083,0.361316,5.606806,4.653194,2.398264,79.870832,28918.541423,9.211111,0.171661
2017-02-26,1564.963013,0.0,1817.410950,0.0,679.171475,0.0,1706.148254,208.350207,82.633334,7.540049,...,24.770834,0.098611,0.039483,8.688750,8.264306,6.636181,86.559028,20726.805461,17.117361,5.030009

In [15]:
op.dummies(df)

AttributeError: module 'Opschaler' has no attribute 'dummies'