"""files: keijzer_hhs_toa_*

stn= Rotterdam(344)
lcd= locatie 
datum= JJJJMMDD
tijd= in UT (1200 UT = 1300 MET = 1400 MEZT)
WW=Weercode automatisch station in code.
VV=Horizontaal zicht (10 min. gemiddeld) in meters.
P=Luchtdruk op NAP (MSL)  (1 min. gem.) in hPa.
Indien een gegeven ontbreekt dan spaties op de betreffende posities.
  stn,lcd     ,datum   ,tijd,    WW,    VV,P 
  344,24t     ,20150101,  10,    10,  4150,1034.0
  344,24t     ,20150101,  20,    10,  3650,1033.9
  344,24t     ,20150101,  30,    10,  3151,1034.3
  344,24t     ,20150101,  40,    10,  5830,1034.1

files: keijzer_hhs_toc_*

stn= Rotterdam(344)
lcd= locatie 
datum= JJJJMMDD
tijd= in UT (1200 UT = 1300 MET = 1400 MEZT)
N=Totale bedekkingsgraad bewolking in okta.
Indien een gegeven ontbreekt dan spaties op de betreffende posities.
  stn,lcd     ,datum   ,tijd,     N
  344,24t     ,20150101,  10,     0
  344,24t     ,20150101,  20,     0
  344,24t     ,20150101,  30,     0
  344,24t     ,20150101,  40,     0

files: keijzer_hhs_tor_*

stn= Rotterdam(344)
lcd= locatie 
datum= JJJJMMDD
tijd= in UT (1200 UT = 1300 MET = 1400 MEZT)
RG=Neerslag intensiteit  Regenmeter (10 min. gem.) in mm/uur.(delen door 6)
DR=Neerslagduur PWS (10 min. som) in seconden.(delen door 600)
Indien een gegeven ontbreekt dan spaties op de betreffende posities.
  stn,lcd     ,datum   ,tijd,    RG,    DR 
  344,24t     ,20150101,  10,     0,     0
  344,24t     ,20150101,  20,     0,     0
  344,24t     ,20150101,  30,     0,     0
  344,24t     ,20150101,  40,     0,     0

files: keijzer_hhs_tos_*

stn= Rotterdam(344)
lcd= locatie 
datum= JJJJMMDD
tijd= in UT (1200 UT = 1300 MET = 1400 MEZT)
Q=Globale straling 10 min. gemiddeld in W/m2.
SQ=Zonneschijnduur in minuten.
Indien een gegeven ontbreekt dan spaties op de betreffende posities.
  stn,lcd     ,datum   ,tijd,     Q,    SQ 
  344,24t     ,20150101,  10,     0,     0
  344,24t     ,20150101,  20,     0,     0
  344,24t     ,20150101,  30,     0,     0
  344,24t     ,20150101,  40,     0,     0

files: keijzer_hhs_tot_*

stn= Rotterdam(344)
lcd= locatie 
datum= JJJJMMDD
tijd= in UT (1200 UT = 1300 MET = 1400 MEZT)
T10=Minimum Gras temperatuur 10 cm (over 10 min) in graden Celsius.
TD=Dauwpunts temperatuur (1 min. gem) in graden Celsius.
T=Temperatuur 1 min gemiddeld (1,5 m hoogte) in graden Celsius.
U=Relatieve vochtigheid 1,5 m  1min. gemiddeld in procenten.
Indien een gegeven ontbreekt dan spaties op de betreffende posities.
  stn,lcd     ,datum   ,tijd,   T10,    TD,     T,     U 
  344,24t     ,20150101,  10,   2.2,   1.3,   3.5,    85
  344,24t     ,20150101,  20,   2.3,     1,   3.2,    85
  344,24t     ,20150101,  30,   2.1,    .9,   3.1,    85
  344,24t     ,20150101,  40,   2.1,     1,   3.4,    84


files: keijzer_hhs_tow_*

stn= Rotterdam(344)
lcd= locatie 
datum= JJJJMMDD
tijd= in UT (1200 UT = 1300 MET = 1400 MEZT)
DD=Gemiddelde windrichting in graden.
FF=Gemiddelde windsnelheid (op 10 m) in m/s.
FX=Maximum windstoot (op 10 m.) in m/s.
Indien een gegeven ontbreekt dan spaties op de betreffende posities.
  stn,lcd     ,datum   ,tijd,    DD,    FF,    FX
  344,24t     ,20150101,  10, 209.8,  5.36,  7.52
  344,24t     ,20150101,  20, 200.7,  4.97,   6.9
  344,24t     ,20150101,  30,   209,  4.84,  6.84
  344,24t     ,20150101,  40, 212.9,  5.03,   6.7
 """

In [15]:
import glob
import pandas as pd

dir = '//datc//opschaler//weather_data//knmi_10_min_raw_data//'
pattern = 'keijzer_hhs_****.LST'

files = glob.glob(dir+pattern) # Get a list of all the files

In [16]:
files

['//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tot_2017.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_toa_2018.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tow_2016.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tot_2016.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tor_2015.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tot_2015.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_toc_2017.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_toc_2018.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tor_2018.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_toc_2016.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tor_2016.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_toa_2016.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tor_2017.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tow_2017.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tos_2017.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_toa_2015.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tos_2016.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tow_2018.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tow_2015.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_toc_2015.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tot_2018.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tos_2015.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_tos_2018.LST',
 '//datc//opschaler//weather_data//knmi_10_min_raw_data/keijzer_hhs_toa_2017.LST']

In [35]:
# Get the file labels (tot, toa, tor, tow)

file_labels = []

for file in files:
    file_labels.append(file[-12:-9])

file_labels

['tot',
 'toa',
 'tow',
 'tot',
 'tor',
 'tot',
 'toc',
 'toc',
 'tor',
 'toc',
 'tor',
 'toa',
 'tor',
 'tow',
 'tos',
 'toa',
 'tos',
 'tow',
 'tow',
 'toc',
 'tot',
 'tos',
 'tos',
 'toa']

In [38]:
toa_names = ['stn', 'lcd', 'datum', 'tijd', 'WW', 'VV', 'P']
toc_names = ['stn', 'lcd', 'datum', 'tijd', 'N']
tor_names = ['stn', 'lcd', 'datum', 'tijd', 'RG', 'DR']
tos_names = ['stn', 'lcd', 'datum', 'tijd', 'Q', 'SQ']
tot_names = ['stn', 'lcd', 'datum', 'tijd', 'T10', 'TD', 'T', 'U']
tow_names = ['stn', 'lcd', 'datum', 'tijd', 'DD', 'FF', 'FX']

dfs = []

for i,file in enumerate(files):
    if file_labels[i] == 'toa':
        column_names = toa_names
    elif file_labels[i] == 'toc':
        column_names = toc_names
    elif file_labels[i] == 'tor':
        column_names = tor_names
    elif file_labels[i] == 'tos':
        column_names = tos_names
    elif file_labels[i] == 'tot':
        column_names = tot_names
    elif file_labels[i] == 'tow':
        column_names = tow_names
    else:
        print('Filelabel not known.')
        print('i = %s , file_labels = %s' %(i, file_labels[i]))
        
    df = pd.read_csv(file, header=0, names=column_names)
    dfs.append(df)

dfs[0]

       stn       lcd     datum  tijd  T10   TD     T     U
0      344  24t       20170101    20  1.8  1.6   1.8  99.0
1      344  24t       20170101    30  1.8  1.9   2.0  99.0
2      344  24t       20170101    40  1.9  2.0   2.1  99.0
3      344  24t       20170101    50  2.0  1.9   2.0  98.0
4      344  24t       20170101   100  1.9  1.9   2.0  98.0
5      344  24t       20170101   110  1.8  1.7   1.8  98.0
6      344  24t       20170101   120  1.8  1.7   1.9  99.0
7      344  24t       20170101   130  1.9  1.8   2.0  99.0
8      344  24t       20170101   140  1.9  1.7   1.9  98.0
9      344  24t       20170101   150  1.9  1.7   1.9  98.0
10     344  24t       20170101   200  1.9  1.8   1.9  99.0
11     344  24t       20170101   210  1.9  1.7   1.9  98.0
12     344  24t       20170101   220  1.9  1.8   1.9  99.0
13     344  24t       20170101   230  1.9  1.7   1.8  98.0
14     344  24t       20170101   240  1.9  1.7   1.8  98.0
15     344  24t       20170101   250  1.8  1.6   1.8  98.0
16     344  24t       20170101   300  1.6  1.5   1.6  98.0
17     344  24t       20170101   310  1.6  1.5   1.6  98.0
18     344  24t       20170101   320  1.6  1.5   1.7  99.0
19     344  24t       20170101   330  1.7  1.5   1.6  98.0
20     344  24t       20170101   340  1.6  1.4   1.6  98.0
21     344  24t       20170101   350  1.6  1.5   1.7  98.0
22     344  24t       20170101   400  1.7  1.5   1.8  98.0
23     344  24t       20170101   410  1.7  1.4   1.7  97.0
24     344  24t       20170101   420  1.6  1.3   1.6  97.0
25     344  24t       20170101   430  1.5  1.2   1.6  97.0
26     344  24t       20170101   440  1.5  1.0   1.5  97.0
27     344  24t       20170101   450  1.3  1.0   1.3  97.0
28     344  24t       20170101   500  1.2  0.7   1.1  97.0
29     344  24t       20170101   510  1.1  0.6   1.1  96.0
...    ...       ...       ...   ...  ...  ...   ...   ...
52529  344  24t       20171231  1910  9.3  8.7  10.3  90.0
52530  344  24t       20171231  1920  9.3  8.5  10.3  89.0
52531  344  24t       20171231  1930  9.3  8.2  10.2  87.0
52532  344  24t       20171231  1940  9.2  8.1  10.0  88.0
52533  344  24t       20171231  1950  9.1  8.0  10.0  87.0
52534  344  24t       20171231  2000  9.1  7.9  10.0  86.0
52535  344  24t       20171231  2010  9.1  7.8   9.9  86.0
52536  344  24t       20171231  2020  9.1  7.6   9.8  86.0
52537  344  24t       20171231  2030  9.1  7.4   9.9  84.0
52538  344  24t       20171231  2040  8.9  7.1   9.7  83.0
52539  344  24t       20171231  2050  8.7  6.8   9.8  82.0
52540  344  24t       20171231  2100  8.7  6.6   9.6  81.0
52541  344  24t       20171231  2110  8.6  6.6   9.6  81.0
52542  344  24t       20171231  2120  8.6  6.5   9.5  81.0
52543  344  24t       20171231  2130  8.6  6.4   9.4  81.0
52544  344  24t       20171231  2140  8.5  6.1   9.4  80.0
52545  344  24t       20171231  2150  8.3  5.8   9.1  79.0
52546  344  24t       20171231  2200  8.1  5.6   9.0  79.0
52547  344  24t       20171231  2210  8.0  5.1   8.9  77.0
52548  344  24t       20171231  2220  7.9  4.9   8.9  76.0
52549  344  24t       20171231  2230  7.8  4.9   8.8  76.0
52550  344  24t       20171231  2240  7.8  5.1   9.0  76.0
52551  344  24t       20171231  2250  7.9  5.1   8.9  77.0
52552  344  24t       20171231  2300  7.8  5.0   8.9  76.0
52553  344  24t       20171231  2310  7.9  5.2   8.7  78.0
52554  344  24t       20171231  2320  7.9  5.3   8.6  80.0
52555  344  24t       20171231  2330  7.7  5.0   8.8  77.0
52556  344  24t       20171231  2340  7.8  4.7   8.9  75.0
52557  344  24t       20171231  2350  7.7  4.5   8.6  75.0
52558  344  24t       20171231  2400  7.7  4.4   8.5  75.0

[52559 rows x 8 columns]

In [ ]:
df.head()